import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "~/views/components/NavBar";
import Footer from "~/views/components/Footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
// import { QueryClient, QueryClientProvider } from 'react-query';  

// import Navbar from "~/app/_components/Navbar";  
// const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <SessionProvider>
          <TRPCReactProvider>
            <main className="flex flex-col min-h-screen">
              <Navbar/>
              {children}
              <Footer/>
            </main>
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}



